baseURL = "http://wilspi.com"
languageCode = "en-us"
title = "Sourabh Deokar | wilspi"
theme = "anatole"
enableEmoji = true
enableRobotsTXT = true


[params]
title = "I'm Sourabh Deokar"
author = "wilspi"
description = "Call me wilspi"
profilePicture = "images/dp.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
#images = ["images/site-feature-image.png"]


## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".


## Social links
[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/wilspi/"

[[params.socialIcons]]
icon = "fa-instagram"
title = "Instagram"
url = "https://www.instagram.com/wilspi/"

[[params.socialIcons]]
icon = "fa-twitter"
title = "Twitter"
url = "https://www.twitter.com/iamwilspi"


## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"
